### ISSUE TITLE
Cadastrar Funcionários

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#1]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração
- [x] Adicionar Tabelas no Projeto de Banco de Dados

### Validações / Implementações
- [x] não pode cadastrar funcionarios duplicados
- [x] caracteres da senha com asteriscos e botão para visualizar a senha (tela)
- [x] campo de salario somente numeros (tela)
- [x] nome sem caracteres especiais e no minimo 2 caracteres
- [x] validar telefone (dominio)
- [x] validar email (dominio)
- [x] corrigir endereço (validador)
- [x] regex para letras diferentes (ç, ~, etc)

### Observações
- Analisar melhores tipos de campo para o banco de dados
    - senha hasheada
    - telefone com ou sem mascara?
    - inativar ou excluir o funcionário?

### Classe
- Login
- Senha
- Salário
- Data de Admissão

![Image](https://user-images.githubusercontent.com/42875143/175298813-e02fd008-be2a-46d6-bf4b-0ea399244104.png)
