### ISSUE TITLE
Módulo Condutores

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#14]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração
- [x] Adicionar Tabelas no Projeto de Banco de Dados

### Validações / Implementações (CLASSE)
- [x] não pode nome com menos de 2 caracteres (validador)
- [x] nome não pode ter caracteres especiais (validador)
- [x] não pode cadastrar duplicados (repositorio)
- [x] regex para letras diferentes (ç, ~, etc)
- [x] se cliente selecionado for pessoa física e checkbox estiver marcado, receber informações do próprio cliente
- [x] ao selecionar pessoa jurídica, desabilitar checkbox
- [x] validar inserção de condutores iguais mas para clientes diferentes
- [x] não pode inserir condutor sem um cliente selecionado
- [x] retornar cliente selecionado no campo de condutor
- [x] não pode excluir um cliente se estiver selecionado em um condutor

### Classe
- Nome
- CPF
- Email
- Telefone
- Endereco
- CNH
- Validade CNH

![Image](https://user-images.githubusercontent.com/42875143/176953300-27eabf42-bdb3-4dde-9e81-22fb56233f96.png)
