### ISSUE TITLE
Módulo Plano de Cobrança

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#16]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração
- [x] Adicionar Tabelas no Projeto de Banco de Dados

### Validações / Implementações (CLASSE)
- [x] não pode cadastrar duplicados (repositorio)

### Classe

IMAGENS

![Image](https://user-images.githubusercontent.com/91919191/177019235-b380dc14-a48b-4562-85ee-7b5eeda1890f.jpeg)

vai ser nessa pegada mesmo ^
