### ISSUE TITLE
Refatoração Cliente

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#19]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração
- [x] Adicionar Tabelas no Projeto de Banco de Dados

### Validações / Implementações (CLASSE)
- [x] não pode nome com menos de 2 caracteres (validador)
- [x] nome não pode ter caracteres especiais (validador)
- [x] não pode cadastrar duplicados (repositorio)
- [x] regex para letras diferentes (ç, ~, etc)

### Classe
- Nome
- Email
- Telefone
- Endereco
- CPF
- CNPJ
- TipoCliente

![Image](https://user-images.githubusercontent.com/42875143/177013604-8500fee7-cdbf-4407-bb13-a4554a61a293.png)
