### ISSUE TITLE
Locação

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#28]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Infra
- [x] Testes Unitários
- [ ] Testes de Integração

### Validações / Implementações (CLASSE)
- Não pode inserir uma locação sem selecionar:
- [x] um cliente
    - exibir condutores somente do cliente selecionado
- [x] um condutor
- [x] um grupo de veículos
    - exibir veículos somente do grupo selecionado
- [x] um veículo
- [x] um plano de cobrança
    - aplicar valores somente do grupo selecionado
- [x] calcular kilometragem do veículo
- [x] data de locação
    - não pode escolher uma data anterior do dia atual
- [x] data de devolução prevista
    - não pode escolher uma data anterior do dia atual
- [x] Valor Total Previsto
    - Calcular com base no plano de cobrança e adicionais das taxas selecionadas
- [x] não pode alugar um veículo que ainda não foi devolvido
- [x] salvar taxas selecionadas
- [x] verificar tipos de taxas para calculos
- [x] não pode permitir excluir um condutor ligado a uma locação
- [x] não pode permitir excluir um veiculo ligado a uma locação
- [x] não pode permitir excluir um plano de cobrança ligado a uma locação
- [x] não pode permitir excluir uma taxa ligada a uma locação

### Classe

- Cliente
- Condutor
- GrupoVeiculos
- Veiculo
- PlanoCobranca
- DataLocacao
- DevolucaoPrevista
- TaxasSelecionadas
- ValorTotalPrevisto

![Image](https://user-images.githubusercontent.com/42875143/181068009-282458bb-4a00-4325-881e-423aa69074f5.png)
