### ISSUE TITLE
Cadastrar Pessoa Jurídica

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#4]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração
- [x] Adicionar Tabelas no Projeto de Banco de Dados

### Validações / Implementações (Pessoa Jurídica)
- [x] não pode nome com menos de 2 caracteres (validador)
- [x] nome não pode ter caracteres especiais (validador)
- [x] não pode cadastrar duplicados (repositorio)
- [x] CNPJ válido (validador)
- [x] máscara CNPJ (tela)
- [x] regex para letras diferentes (ç, ~, etc)

Regex CNPJ: ^[0-9]{2}.[0-9]{3}.[0-9]{3}\/[0-9]{4}-[0-9]{2}$

### Classe Pessoa Jurídica
- CNPJ

![Image](https://user-images.githubusercontent.com/42875143/176006035-b1ef19f2-7d7d-4a5a-8d75-3cb0bd3d2149.png)
