### ISSUE TITLE
Cadastrar Pessoa Física

### ISSUE THREAD

**Issue by slackbot115** [Delete-Sem-Where/Locadora-De-Veiculos#8]
### Tasks
- [x] Tela
- [x] Dominio
- [x] Validações
- [x] Infra
- [x] Testes Unitários
- [x] Testes de Integração

### Validações / Implementações (Pessoa Física)
- [x] não pode cadastrar funcionarios duplicados
- [x] nome sem caracteres especiais e no minimo 2 caracteres
- [x] validar telefone (dominio)
- [x] validar email (dominio)
- [x] corrigir endereço (validador)
- [ ] CPF válido (validador)
- [ ] máscara CPF (tela)
- [x] regex para letras diferentes (ç, ~, etc)

### Classe Pessoa Física
- CPF
- CNH

![Image](https://user-images.githubusercontent.com/42875143/175299173-d66da36e-3a24-4d80-b0d2-8845ca35425a.png)
